architecture: railight
backbone: vgg16
num_exp: exp3.da.batch8.weak_strong_augmentation.caotulab_server.h100

batch_size: 8

lr: 5.0e-4
momentum: 0.9
weight_decay: 5.0e-4
gamma: 0.1
epochs: 100
max_steps: 340000
lr_steps: [170000, 250000, 310000]

cuda: true
gpu_ids: 0
num_workers: 4
local_rank: 0

source_train_file: /home/a00161/stacy.en14/data/data_exp2/railight/8/dataset/source_train.txt
source_val_file:   /home/a00161/stacy.en14/data/data_exp2/railight/8/dataset/source_val.txt
source_test_file:  /home/a00161/stacy.en14/data/data_exp2/railight/8/dataset/source_test.txt
target_train_file: /home/a00161/stacy.en14/data/data_exp2/railight/8/dataset/target_train.txt
target_val_file:   /home/a00161/stacy.en14/data/data_exp2/railight/8/dataset/target_val.txt
target_test_file:  /home/a00161/stacy.en14/data/data_exp2/railight/8/dataset/target_test.txt

nc: 8
names: ['fastener_1', 'critical_crack', 'fastener_2', 'sleeper_l', 'sleeper_r', 'missing_items', 'broken_sleeper', 'minor_crack']

save_folder: /home/a00161/stacy.en14/data/data_exp2/railight/weights
charts_dir:  /home/a00161/stacy.en14/data/data_exp2/railight/charts
records_dir: /home/a00161/stacy.en14/data/data_exp2/railight/records
log_dir:     /home/a00161/stacy.en14/data/data_exp2/railight/logs
resume: true

val_every_epochs: 3
viz_num_samples: 6
viz_every_iters: 500
viz_full_every_epochs: 10
viz_max_source_batches: 30
viz_max_target_batches: 30

kl_loss_weight: 1.0
target_loss_weight: 0.1
is_use_supervised_target_loss: true
supervised_target_loss_weight: 1.0

focal_enabled: true
focal_gamma: 2.0
focal_alpha_bg: 0.25

box_loss: smooth_l1
is_use_rc_loss: false

use_wandb: true
wandb_project: da-rdd-railight
wandb_entity: null
wandb_dir: /home/a00161/stacy.en14/data/data_exp2/railight/wandb

pseudo_weight: 1.0
pseudo_conf: 0.8
pseudo_start_iters: 20000
ema_decay: 0.9996

source_strong_weight: 1.0
pseudo_strong_aug: true
strong_aug_jitter_p: 0.8
strong_aug_brightness: 0.4
strong_aug_contrast: 0.4
strong_aug_saturation: 0.4
strong_aug_hue: 0.1
strong_aug_gray_p: 0.2
strong_aug_blur_p: 0.5
strong_aug_blur_sigma: [0.1, 2.0]
strong_aug_erase_p: [0.7, 0.5, 0.3]
cat_viz_per_class: 6
