architecture: dai_net
backbone: yolo26n
num_exp: exp1

pretrained_model: weights/yolo26n.pt

batch_size: 4

lr: 5.0e-4
momentum: 0.9
weight_decay: 1e-6
gamma: 0.1
epochs: 100
max_steps: 340000
lr_steps: [170000, 250000, 310000]

cuda: true
gpu_ids: 5,7
num_workers: 2
local_rank: 0

source_train_file: ./dataset/source_train.txt
source_val_file:   ./dataset/source_val.txt
source_test_file:  ./dataset/source_test.txt
target_train_file: ./dataset/target_train.txt
target_val_file:   ./dataset/target_val.txt
target_test_file:  ./dataset/target_test.txt
target_folder4unsupervised: null

nc: 8
names: ['fastener_1', 'critical_crack', 'fastener_2', 'sleeper_l', 'sleeper_r', 'missing_items', 'broken_sleeper', 'minor_crack']

kl_loss_weight: 1.0
target_loss_weight: 0.1

focal_enabled: true
focal_gamma: 2.0
focal_alpha_bg: 0.25
focal_class_weights:
  critical_crack: 2.0
  minor_crack: 2.0
  broken_sleeper: 2.0

box_loss: smooth_l1
is_use_rc_loss: false

use_wandb: true
wandb_project: uda-rdd-idayolo

save_folder: weights/
charts_dir:  ./charts
resume: true

val_every_epochs: 3
viz_num_samples: 6
viz_every_iters: 500
viz_full_every_epochs: 10
viz_max_source_batches: 30
viz_max_target_batches: 30
