from __future__ import annotations

from typing import Any, Dict

__all__ = [
    "TRAIN_DEFAULTS",
    "TEST_DEFAULTS",
    "WANDB_EPOCH_KEYS",
    "_TRAIN_DEFAULTS",
    "_TEST_DEFAULTS",
    "_WANDB_EPOCH_KEYS",
]

TRAIN_DEFAULTS: Dict[str, Any] = {
    "batch_size": 4,
    "num_workers": 0,
    "cuda": True,
    "lr": 0.0005,
    "momentum": 0.9,
    "weight_decay": 0.0005,
    "gamma": 0.1,
    "gpu_ids": 0,
    "save_folder": "weights/",
    "source_train_file": "./dataset/source_train.txt",
    "source_val_file": "./dataset/source_val.txt",
    "source_test_file": "./dataset/source_test.txt",
    "nc": 3,
    "names": None,
    "charts_dir": "./charts",
    "records_dir": "./records",
    "viz_num_samples": 6,
    "viz_every_iters": 500,
    "viz_full_every_epochs": 1,
    "resume": None,
    "kl_loss_weight": 1.0,
    "target_loss_weight": 0.05,
    "wreg_loss_weight": 0.0001,
    "entropy_loss_weight": 0.01,
    "optimizer": "sgd",
    "muon_ratio": 0.5,
    "prog_warmup_iters": 0,
    "stal_enabled": False,
    "stal_ref_area": 0.02,
    "stal_max_w": 4.0,
    "mutual_loss_weight": 0.0,
    "pseudo_weight": 0.0,
    "pseudo_conf": 0.7,
    "pseudo_start_iters": 0,
    "pseudo_nms_iou": 0.35,
    "ema_decay": 0.9996,
    "pseudo_strong_aug": True,
    "pseudo_ramp_iters": 1000,
    "is_use_rc_loss": True,
    "target_train_file": "./dataset/target_train.txt",
    "target_val_file": "./dataset/target_val.txt",
    "target_test_file": "./dataset/target_test.txt",
    "target_folder4unsupervised": None,
    "focal_enabled": True,
    "focal_gamma": 2.0,
    "focal_alpha_bg": 0.25,
    "focal_class_weights": None,
    "backbone_scale": None,
    "backbone_weights": "auto",
    "pretrained_model": None,
    "use_wandb": False,
    "wandb_project": "dainet-railway",
    "wandb_entity": None,
    "val_every_epochs": 1,
    "viz_max_source_batches": 30,
    "viz_max_target_batches": 30,
    "box_loss": "smooth_l1",
    "epochs": 100,
    "max_steps": 150000,
    "lr_steps": [20000, 25000, 30000],
}

TEST_DEFAULTS: Dict[str, Any] = {
    "batch_size": 1,
    "num_workers": 0,
    "cuda": True,
    "source_train_file": "./dataset/source_train.txt",
    "source_val_file": "./dataset/source_val.txt",
    "source_test_file": "./dataset/source_test.txt",
    "target_train_file": "./dataset/target_train.txt",
    "target_val_file": "./dataset/target_val.txt",
    "target_test_file": "./dataset/target_test.txt",
    "nc": 3,
    "names": None,
    "source_folder": "",
    "target_folder4unsupervised": "/media/caotulab/303A225B3A221DFA/Nhan/data/images/target",
    "charts_dir": "./charts",
    "records_dir": "./records",
    "mode_name": "test",
    "viz_num_samples": 6,
    "weights": None,
    "iou_thr": 0.5,
    "score_thr_cm": 0.5,
    "nms_iou_thr": 0.35,
    "export_predicted_source_path": None,
    "export_predicted_target_path": None,
    "focal_enabled": True,
    "focal_gamma": 2.0,
    "focal_alpha_bg": 0.25,
    "box_loss": "smooth_l1",
}

WANDB_EPOCH_KEYS: Dict[str, str] = {
    "train_loss_epoch": "train/loss",
    "train_det_epoch": "train/det_loss",
    "val_loss": "val/loss",
    "val_precision": "val/precision",
    "val_recall": "val/recall",
    "val_f1": "val/f1",
    "val_map": "val/mAP",
    "val_kl_st": "val/kl_st",
    "val_entropy": "val/entropy",
    "target_precision": "target/precision",
    "target_recall": "target/recall",
    "target_f1": "target/f1",
    "target_map": "target/mAP",
    "target_val_loss": "target/loss",
}


_TRAIN_DEFAULTS = TRAIN_DEFAULTS
_TEST_DEFAULTS = TEST_DEFAULTS
_WANDB_EPOCH_KEYS = WANDB_EPOCH_KEYS
